using System.Text;

namespace CgMosqCtl;

public static class Renderer
{
    public static string RenderMosquittoConf(BrokerConfig config)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Auto-generated by cg-mosqctl — do not edit manually");
        sb.AppendLine("# Source: cg-broker.yaml");
        sb.AppendLine();
        sb.AppendLine("per_listener_settings true");
        sb.AppendLine();
        sb.AppendLine($"listener {config.Listener.Port} {config.Listener.BindIp}");
        sb.AppendLine();

        if (config.Security.AuthEnabled)
        {
            sb.AppendLine("allow_anonymous false");
            sb.AppendLine($"password_file {config.Security.PasswdPath}");
            sb.AppendLine($"acl_file {config.Security.AclPath}");
        }
        else
        {
            sb.AppendLine("allow_anonymous true");
        }

        sb.AppendLine();

        if (config.Persistence.Enabled)
        {
            sb.AppendLine("persistence true");
            sb.AppendLine($"persistence_location {config.Persistence.Location}");
        }
        else
        {
            sb.AppendLine("persistence false");
        }

        sb.AppendLine();
        sb.AppendLine($"log_dest file {config.Paths.Log}");
        sb.AppendLine($"connection_messages {(config.Logging.ConnectionMessages ? "true" : "false")}");

        return sb.ToString();
    }

    public static string RenderAcl(BrokerConfig config)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Auto-generated by cg-mosqctl — do not edit manually");

        foreach (var user in config.Security.Users)
        {
            sb.AppendLine();
            sb.AppendLine($"user {user.Username}");
            foreach (var topic in user.Topics)
            {
                sb.AppendLine($"topic readwrite {topic}");
            }
        }

        return sb.ToString();
    }

    public static string RenderUsersFile(BrokerConfig config)
    {
        var sb = new StringBuilder();
        foreach (var user in config.Security.Users)
        {
            sb.AppendLine($"{user.Username}:{user.Password}");
        }
        return sb.ToString();
    }
}
